class_name PFStrings
extends RefCounted

## UI 文案集中入口。
## v1.0 前界面先使用英文，后续 i18n 只需要替换这里和对应翻译资源。

const ACTION_NEW := "New"
const ACTION_OPEN := "Open"
const ACTION_SAVE := "Save"
const ACTION_SAVE_AS := "Save As"
const ACTION_BATCH := "Batch"
const ACTION_MATTE := "Matte"
const ACTION_SLICE := "Slice"
const ACTION_OUTLINE := "Outline"
const ACTION_EXPORT_PNG := "Export PNG"
const MENU_FILE := "File"
const MENU_IMPORT_IMAGES := "Import Images..."
const MENU_GENERATE_MOCK_BATCH := "Generate Mock Batch"
const MENU_RUN_SELECTED_GRAPH := "Run Selected Graph"
const STATUS_READY := "Ready"
const STATUS_SAVED := "Saved"
const STATUS_DIRTY := "Unsaved changes"
const STATUS_CLEANUP_EMPTY := "Select one or more sprites to clean"
const STATUS_CLEANUP_QUEUED := "Cleanup queued"
const STATUS_CLEANUP_DONE := "Cleanup complete"
const STATUS_CLEANUP_CANCELED := "Cleanup canceled"
const STATUS_MATTING_QUEUED := "Matting queued"
const STATUS_MATTING_DONE := "Matting complete"
const STATUS_SLICE_QUEUED := "Slicing queued"
const STATUS_SLICE_DONE := "Slicing complete"
const STATUS_OUTLINE_QUEUED := "Outline queued"
const STATUS_OUTLINE_DONE := "Outline complete"
const STATUS_PREVIEW_QUEUED := "Preview queued"
const STATUS_EXPORT_EMPTY := "Select one or more sprites to export"
const STATUS_EXPORTED := "PNG exported"
const STATUS_EXPORT_FAILED := "PNG export failed"
const STATUS_SPRITESHEET_EXPORTED := "Spritesheet exported"
const STATUS_TOOL_OFF := "Move mode"
const STATUS_TOOL_FORMAT := "Tool: %s"
const STATUS_SELECTION_EMPTY := "Selection cleared"
const STATUS_SELECTION_FORMAT := "Selection: %dx%d px, area %d"
const ZOOM_CONTROL_TOOLTIP := "Canvas zoom"
const STATUS_BATCH_NEEDS_SELECTION := "Select two or more sprites to make a batch"
const STATUS_BATCH_SPLIT := "Batch subset created"
const STATUS_BATCH_SPLIT_EMPTY := "Select thumbnails inside a batch before splitting"
const STATUS_BATCH_SPLIT_KEEP := "Kept subset created"
const STATUS_BATCH_SPLIT_KEEP_EMPTY := "Mark at least one kept thumbnail before splitting"
const STATUS_BATCH_MARK_NEEDS_SELECTION := "Select thumbnails inside a batch before marking"
const STATUS_BATCH_MARK_KEEP := "%d thumbnails marked keep"
const STATUS_BATCH_MARK_REJECT := "%d thumbnails marked reject"
const STATUS_BATCH_MARK_FLAG := "%d thumbnails flagged"
const STATUS_BATCH_MARK_CLEAR := "%d thumbnail marks cleared"
const STATUS_MOCK_GENERATE_DONE := "Mock batch generated: %d sprites"
const STATUS_MOCK_GENERATE_FAILED := "Mock batch generation failed"
const STATUS_GRAPH_RUN_DONE := "Graph run complete: %d sprites"
const STATUS_GRAPH_RUN_FAILED := "Graph run failed"
const STATUS_GRAPH_RUN_NEEDS_SELECTION := "Select a graph node or batch before running"
const CLEANUP_TITLE := "Pixel Cleanup"
const CLEANUP_SELECTED_FORMAT := "%d selected"
const CLEANUP_PRESET_PRIOR_FORMAT := "Preset prior: %dpx"
const CLEANUP_AUTO_DETECT := "Auto detect grid"
const CLEANUP_RUN_RESAMPLE := "Run resample"
const CLEANUP_RUN_QUANTIZE := "Run quantize"
const CLEANUP_LABEL_SCALE := "Scale"
const CLEANUP_LABEL_OFFSET_X := "Offset X"
const CLEANUP_LABEL_OFFSET_Y := "Offset Y"
const CLEANUP_LABEL_RESAMPLE := "Resample"
const CLEANUP_LABEL_QUANTIZE := "Quantize"
const CLEANUP_LABEL_AUTO_K_STRATEGY := "Auto K Strategy"
const CLEANUP_LABEL_PALETTE := "Palette"
const CLEANUP_LABEL_MAX_COLORS := "Max Colors"
const CLEANUP_LABEL_DITHER := "Dither"
const CLEANUP_LABEL_STRENGTH := "Strength"
const CLEANUP_LABEL_CHROMA := "Chroma"
const CLEANUP_LABEL_DENSITY := "Density"
const CLEANUP_AUTO_K_TOOLTIP := "K-means is smoother for larger K, but slower."
const CLEANUP_CUSTOM_PALETTE_PREFIX := "Custom: %s"
const CLEANUP_IMPORT_PALETTE_ITEM := "Import custom palette..."
const CLEANUP_DELETE_PALETTE := "Delete Custom Palette"
const CLEANUP_APPLY := "Apply Cleanup"
const CLEANUP_CANCEL := "Cancel Cleanup"
const CLEANUP_NO_REPORT := "No cleanup report"
const CLEANUP_NON_SQUARE_WARNING := "\nNon-square grid warning"
const CLEANUP_REPORT_FORMAT := "Scale %.2f | Confidence %.2f\nColors %d | Output %s%s"
const DIALOG_IMPORT_PALETTE := "Import Custom Palette"
const DIALOG_PALETTE_ERROR := "Palette Import Error"
const PALETTE_IMPORT_FAILED := "Palette import failed."
const DIALOG_OPEN_PROJECT := "Open PixelForge Project"
const DIALOG_SAVE_PROJECT := "Save PixelForge Project"
const DIALOG_IMPORT_IMAGES := "Import Images"
const DIALOG_EXPORT_PNG := "Export PNG"
const DIALOG_NOTICE := "Notice"
const DIALOG_RECOVERY := "Recover Autosave"
const DIALOG_APPLY := "Apply"
const DIALOG_CANCEL := "Cancel"
const DIALOG_MATTE_TITLE := "Matte Background"
const DIALOG_SLICE_TITLE := "Slice Sprites"
const DIALOG_OUTLINE_TITLE := "Outline Sprite"
const DIALOG_MATTE_NON_FLAT_TITLE := "Background Not Uniform"
const DIALOG_MATTE_NON_FLAT_BODY := (
	"The background is not a solid color.\n\n"
	+ "Try the Magic Wand tool to select the background, increase tolerance carefully, "
	+ "or slice directly if the image already has transparency."
)
const DIALOG_ONBOARDING_TITLE := "Welcome to PixelForge"
const DIALOG_ONBOARDING_BODY := (
	"Quick start:\n"
	+ "1. Drag images onto the canvas or use File > Import Images.\n"
	+ "2. Select a sprite and use Matte, Slice, or Outline.\n"
	+ "3. Select multiple sprites and create a Batch for whole-batch actions.\n"
	+ "4. Use the Pixel Cleanup panel to clean one sprite or a selected group."
)
const TOOL_MAGIC_WAND := "Magic Wand"
const TOOL_RECTANGLE := "Rectangle Select"
const TOOL_LASSO := "Lasso"
const MATTE_LABEL_MODE := "Mode"
const MATTE_LABEL_TOLERANCE := "Tolerance"
const MATTE_LABEL_FEATHER := "Feather"
const MATTE_MODE_FLOOD := "Flood from edge"
const MATTE_MODE_GLOBAL := "Global color key"
const MATTE_WARNING_NON_FLAT_BACKGROUND := "Background is not uniform. Use Magic Wand or raise tolerance carefully."
const SLICE_AUTO_MATTE := "Matte before slicing"
const SLICE_LABEL_MERGE_DISTANCE := "Merge Distance"
const SLICE_LABEL_MIN_AREA := "Minimum Area"
const SLICE_PREVIEW_COUNT_FORMAT := "%d segments found"
const OUTLINE_LABEL_TYPE := "Type"
const OUTLINE_LABEL_CORNER := "Corner"
const OUTLINE_LABEL_COLOR := "Color"
const OUTLINE_TYPE_OUTER := "Outer"
const OUTLINE_TYPE_INNER := "Inner"
const OUTLINE_CORNER_CROSS := "Cross"
const OUTLINE_CORNER_SQUARE := "Square"
const OUTLINE_COLORED := "Use colored outline"
const BATCH_DEFAULT_LABEL := "Batch"
const MOCK_BATCH_LABEL := "Mock Batch"
const BATCH_ACTION_CLEANUP := "Clean Batch"
const BATCH_ACTION_MATTE := "Matte Batch"
const BATCH_ACTION_OUTLINE := "Outline Batch"
const BATCH_ACTION_QUANTIZE := "Quantize Batch"
const BATCH_ACTION_MARK_KEEP := "Mark Keep"
const BATCH_ACTION_MARK_REJECT := "Mark Reject"
const BATCH_ACTION_MARK_FLAG := "Flag"
const BATCH_ACTION_CLEAR_MARK := "Clear Mark"
const BATCH_ACTION_SPLIT_KEEP := "Split Kept"
const BATCH_ACTION_SPLIT := "Split Selected"
const BATCH_ACTION_EXPORT := "Export Batch"
const BATCH_ACTION_SEND_TO_EDITOR := "Send to Editor"
const BATCH_KEEP_LABEL_SUFFIX := "keep"
const GRAPH_PARAM_OBJECT_LIST := "Objects"
const GRAPH_PARAM_WIDTH := "Width"
const GRAPH_PARAM_HEIGHT := "Height"
const GRAPH_PARAM_PER_SUBJECT := "Per Subject"
const GRAPH_PARAM_PROVIDER := "Provider"
const GRAPH_PARAM_BATCH_SIZE := "Batch Size"
const GRAPH_PARAM_SEED := "Seed"
