class_name PFStrings
extends RefCounted

## UI 文案集中入口。
## v1.0 前界面先使用英文，后续 i18n 只需要替换这里和对应翻译资源。

const ACTION_NEW := "New"
const ACTION_OPEN := "Open"
const ACTION_SAVE := "Save"
const ACTION_SAVE_AS := "Save As"
const ACTION_EXPORT_PNG := "Export PNG"
const STATUS_READY := "Ready"
const STATUS_SAVED := "Saved"
const STATUS_DIRTY := "Unsaved changes"
const STATUS_CLEANUP_EMPTY := "Select one or more sprites to clean"
const STATUS_CLEANUP_QUEUED := "Cleanup queued"
const STATUS_CLEANUP_DONE := "Cleanup complete"
const STATUS_CLEANUP_CANCELED := "Cleanup canceled"
const STATUS_PREVIEW_QUEUED := "Preview queued"
const STATUS_EXPORT_EMPTY := "Select one sprite to export"
const STATUS_EXPORTED := "PNG exported"
const CLEANUP_TITLE := "Pixel Cleanup"
const CLEANUP_SELECTED_FORMAT := "%d selected"
const CLEANUP_PRESET_PRIOR_FORMAT := "Preset prior: %dpx"
const CLEANUP_AUTO_DETECT := "Auto detect grid"
const CLEANUP_RUN_RESAMPLE := "Run resample"
const CLEANUP_RUN_QUANTIZE := "Run quantize"
const CLEANUP_LABEL_SCALE := "Scale"
const CLEANUP_LABEL_OFFSET_X := "Offset X"
const CLEANUP_LABEL_OFFSET_Y := "Offset Y"
const CLEANUP_LABEL_RESAMPLE := "Resample"
const CLEANUP_LABEL_QUANTIZE := "Quantize"
const CLEANUP_LABEL_AUTO_K_STRATEGY := "Auto K Strategy"
const CLEANUP_LABEL_PALETTE := "Palette"
const CLEANUP_LABEL_MAX_COLORS := "Max Colors"
const CLEANUP_LABEL_DITHER := "Dither"
const CLEANUP_LABEL_STRENGTH := "Strength"
const CLEANUP_LABEL_CHROMA := "Chroma"
const CLEANUP_LABEL_DENSITY := "Density"
const CLEANUP_AUTO_K_TOOLTIP := "K-means is smoother for larger K, but slower."
const CLEANUP_CUSTOM_PALETTE_PREFIX := "Custom: %s"
const CLEANUP_IMPORT_PALETTE_ITEM := "Import custom palette..."
const CLEANUP_DELETE_PALETTE := "Delete Custom Palette"
const CLEANUP_APPLY := "Apply Cleanup"
const CLEANUP_CANCEL := "Cancel Cleanup"
const CLEANUP_NO_REPORT := "No cleanup report"
const CLEANUP_NON_SQUARE_WARNING := "\nNon-square grid warning"
const CLEANUP_REPORT_FORMAT := "Scale %.2f | Confidence %.2f\nColors %d | Output %s%s"
const DIALOG_IMPORT_PALETTE := "Import Custom Palette"
const DIALOG_PALETTE_ERROR := "Palette Import Error"
const PALETTE_IMPORT_FAILED := "Palette import failed."
const DIALOG_OPEN_PROJECT := "Open PixelForge Project"
const DIALOG_SAVE_PROJECT := "Save PixelForge Project"
const DIALOG_EXPORT_PNG := "Export PNG"
const DIALOG_RECOVERY := "Recover Autosave"
