class_name PFStrings
extends RefCounted

## UI 文案集中入口。
## v1.0 前界面先使用英文，后续 i18n 只需要替换这里和对应翻译资源。

const ACTION_NEW := "New"
const ACTION_OPEN := "Open"
const ACTION_SAVE := "Save"
const ACTION_SAVE_AS := "Save As"
const ACTION_QUIT := "Quit"
const ACTION_RECOVER := "Recover Autosave"
const ACTION_IMPORT_IMAGES := "Import Images..."
const ACTION_FOCUS_LAST_IMPORT := "Focus Last Import"
const ACTION_RETRY_IMPORT := "Retry Import"
const ACTION_OVERWRITE := "Overwrite"
const ACTION_OPEN_EXPORT_FOLDER := "Open Folder"
const ACTION_CLOSE := "Close"
const ACTION_SAVE_PROVIDER := "Save Credentials"
const ACTION_VALIDATE_PROVIDER := "Validate"
const ACTION_USE_FOR_SESSION := "Use for Session"
const ACTION_BATCH := "Batch"
const ACTION_MATTE := "Matte"
const ACTION_SLICE := "Slice"
const ACTION_OUTLINE := "Outline"
const ACTION_EXPORT_PNG := "Export PNG"
const MENU_FILE := "File"
const MENU_IMPORT_IMAGES := "Import Images..."
const MENU_GENERATE_MOCK_BATCH := "Generate Mock Batch"
const MENU_CONFIGURE_OPENAI_SESSION := "Configure OpenAI Session..."
const MENU_PROVIDER_SETTINGS := "Provider Settings..."
const MENU_GENERATE_OPENAI_BATCH := "Generate OpenAI Batch"
const MENU_RUN_SELECTED_GRAPH := "Run Selected Graph"
const MENU_ADD_GRAPH_NODE := "Add Graph Node"
const MENU_EDIT_SELECTED_GRAPH_NODE := "Edit Selected Graph Node..."
const MENU_OPEN_BOARD := "Open Board Editor..."
const STATUS_READY := "Ready"
const STATUS_SAVED := "Saved"
const STATUS_DIRTY := "Unsaved changes"
const STATUS_PROJECT_SAVE_FAILED_FORMAT := (
	"Save failed for %s (%s). " + "Check the folder permissions or choose Save As and try again."
)
const STATUS_PROJECT_OPEN_FAILED_FORMAT := (
	"Open failed for %s (%s). " + "Check that the file exists and is a valid PixelForge project."
)
const STATUS_AUTOSAVE_FAILED_FORMAT := "Autosave failed in %s (%s). Save the project manually to a writable folder."
const STATUS_RECOVERY_COMPLETE := "Autosave recovered as an unsaved copy. Use Save to choose a new project file."
const STATUS_CLEANUP_EMPTY := "Select one or more sprites to clean"
const STATUS_CLEANUP_QUEUED := "Cleanup queued"
const STATUS_CLEANUP_DONE := "Cleanup complete"
const STATUS_CLEANUP_CANCELED := "Cleanup canceled"
const STATUS_MATTING_QUEUED := "Matting queued"
const STATUS_MATTING_DONE := "Matting complete"
const STATUS_SLICE_QUEUED := "Slicing queued"
const STATUS_SLICE_DONE := "Slicing complete"
const STATUS_OUTLINE_QUEUED := "Outline queued"
const STATUS_OUTLINE_DONE := "Outline complete"
const STATUS_PREVIEW_QUEUED := "Preview queued"
const STATUS_PREVIEW_RUNNING_FORMAT := "Cleanup preview: %d%%"
const STATUS_PREVIEW_DONE := "Cleanup preview ready"
const STATUS_PREVIEW_CANCELED := "Cleanup preview canceled"
const STATUS_TASK_RUNNING_FORMAT := "%s: %d%%"
const STATUS_TASK_FAILED := "Processing failed. Check the input and try again."
const STATUS_TASK_CANCELED := "Processing canceled"
const TASK_MATTING := "Matting"
const TASK_SLICING := "Slicing"
const TASK_OUTLINE := "Outline"
const TASK_CLEANUP := "Cleanup"
const STATUS_IMPORT_DONE_FORMAT := "Imported %d image(s) at the current view. Use File > Focus Last Import to return."
const STATUS_IMPORT_FOCUSED := "Focused the last import"
const STATUS_IMPORT_FAILED_FORMAT := "Import failed: %s. Choose Retry Import after fixing the files."
const STATUS_EXPORT_EMPTY := "Select one or more sprites to export"
const STATUS_EXPORTED := "PNG exported"
const STATUS_EXPORT_FAILED := "PNG export failed"
const STATUS_SPRITESHEET_EXPORTED := "Spritesheet exported"
const STATUS_EXPORT_SUCCESS_FORMAT := "Exported to %s"
const STATUS_EXPORT_CANCELED := "Export canceled; existing files were not changed"
const STATUS_EXPORT_FAILED_DETAIL_FORMAT := "Export failed (%s). %s %s"
const EXPORT_NONE_CREATED := "No output files were created."
const EXPORT_CREATED_FORMAT := "Created: %s."
const EXPORT_MISSING_FORMAT := "Not created: %s. Choose another folder or retry."
const STATUS_TOOL_OFF := "Move mode"
const STATUS_TOOL_FORMAT := "Tool: %s"
const STATUS_SELECTION_EMPTY := "Selection cleared"
const STATUS_SELECTION_FORMAT := "Selection: %dx%d px, area %d"
const ZOOM_CONTROL_TOOLTIP := "Canvas zoom"
const STATUS_BATCH_NEEDS_SELECTION := "Select two or more sprites to make a batch"
const STATUS_BATCH_SPLIT := "Batch subset created"
const STATUS_BATCH_SPLIT_EMPTY := "Select thumbnails inside a batch before splitting"
const STATUS_BATCH_SPLIT_KEEP := "Kept subset created"
const STATUS_BATCH_SPLIT_KEEP_EMPTY := "Mark at least one kept thumbnail before splitting"
const STATUS_BATCH_MARK_NEEDS_SELECTION := "Select thumbnails inside a batch before marking"
const STATUS_BATCH_MARK_KEEP := "%d thumbnails marked keep"
const STATUS_BATCH_MARK_REJECT := "%d thumbnails marked reject"
const STATUS_BATCH_MARK_FLAG := "%d thumbnails flagged"
const STATUS_BATCH_MARK_CLEAR := "%d thumbnail marks cleared"
const STATUS_BATCH_SHOW_ALL := "Showing all thumbnails"
const STATUS_BATCH_SHOW_KEEP := "Showing kept thumbnails"
const STATUS_BATCH_SHOW_PENDING := "Showing pending thumbnails"
const STATUS_BATCH_SHOW_REJECT := "Showing rejected thumbnails"
const STATUS_BATCH_SHOW_FLAG := "Showing flagged thumbnails"
const STATUS_BATCH_FILTER_FAILED := "Batch filter failed"
const STATUS_BATCH_LAYOUT_CONTACT := "Showing contact sheet"
const STATUS_BATCH_LAYOUT_FOCUS := "Showing focus view"
const STATUS_BATCH_LAYOUT_FAILED := "Batch layout failed"
const STATUS_BATCH_FOCUS_EMPTY := "No visible thumbnails in batch"
const STATUS_BATCH_FOCUS_FORMAT := "Focused thumbnail %d of %d"
const STATUS_BATCH_COMPARE_CURRENT := "Showing current batch"
const STATUS_BATCH_COMPARE_PREVIOUS := "Showing previous batch"
const STATUS_BATCH_COMPARE_SPLIT := "Showing before/after compare"
const STATUS_BATCH_COMPARE_EMPTY := "No previous batch version"
const STATUS_MOCK_GENERATE_DONE := "Mock batch generated: %d sprites"
const STATUS_MOCK_GENERATE_FAILED := "Mock batch generation failed"
const STATUS_OPENAI_SESSION_READY := "OpenAI key configured for this session only"
const STATUS_OPENAI_SESSION_REQUIRED := "Configure an OpenAI session key before generating"
const STATUS_OPENAI_GENERATE_QUEUED := "OpenAI generation queued"
const STATUS_OPENAI_GENERATE_RUNNING_FORMAT := "OpenAI generation: %d%% — %s"
const STATUS_OPENAI_GENERATE_DONE := "OpenAI batch generated: %d sprites"
const STATUS_OPENAI_GENERATE_FAILED_FORMAT := "OpenAI generation failed: %s. Check the key or network and retry."
const STATUS_OPENAI_GENERATE_CANCELED := "OpenAI generation canceled"
const STATUS_PROVIDER_CREDENTIALS_REQUIRED_FORMAT := (
	"Configure and validate %s in Provider Settings " + "before running this graph"
)
const STATUS_PROVIDER_GENERATE_QUEUED_FORMAT := "%s generation queued"
const STATUS_PROVIDER_GENERATE_RUNNING_FORMAT := "%s generation: %d%% — %s"
const STATUS_PROVIDER_GENERATE_DONE_FORMAT := "%s batch generated: %d sprites"
const STATUS_PROVIDER_GENERATE_FAILED_FORMAT := "%s generation failed: %s"
const STATUS_PROVIDER_GENERATE_CANCELED_FORMAT := "%s generation canceled"
const STATUS_PROVIDER_BUDGET_CONFIRM_FORMAT := (
	"Estimated $%.2f would exceed the $%.2f monthly budget. " + "Confirm to continue."
)
const COST_MONTH_FORMAT := "This month: $%.2f"
const COST_MONTH_ESTIMATE_FORMAT := "This month: $%.2f · Next ≈$%.2f"
const PROVIDER_MONTHLY_BUDGET := "Monthly AI budget (USD, 0 = no limit)"
const DIALOG_PROVIDER_BUDGET_TITLE := "Confirm AI generation cost"
const DIALOG_BOARD_TITLE := "Board Editor"
const BOARD_ASSETS := "Assets and Animations"
const BOARD_SEARCH_ASSETS := "Search name or tag"
const BOARD_LAYERS := "Layers"
const BOARD_ADD_TILE_LAYER := "+ Tile"
const BOARD_ADD_FREE_LAYER := "+ Free"
const BOARD_LAYER_UP := "Up"
const BOARD_LAYER_DOWN := "Down"
const BOARD_LAYER_VISIBLE := "Show / Hide"
const BOARD_DELETE_LAYER := "Delete Layer"
const BOARD_OPACITY := "Opacity"
const BOARD_DEFINE_TERRAIN_16 := "Define 16-Blob from Selection"
const BOARD_DEFINE_TERRAIN_47 := "Define 47-Blob from Selection"
const BOARD_CREATE_ANIMATION := "Create Animation from Selection"
const BOARD_TOOL_PAINT := "Paint"
const BOARD_TOOL_RECT := "Rectangle"
const BOARD_TOOL_FILL := "Flood Fill"
const BOARD_PLAY_PAUSE := "Play / Pause"
const BOARD_EXPORT := "Export Scene"
const BOARD_TERRAIN_NEEDS_16 := "Select at least 16 static assets in role order"
const BOARD_TERRAIN_READY := "16-blob terrain brush ready"
const BOARD_TERRAIN_NEEDS_47 := "Select at least 47 static assets in canonical role order"
const BOARD_TERRAIN_47_READY := "47-blob terrain brush ready"
const BOARD_TERRAIN_FALLBACK := "%d terrain cells used nearest-role fallback"
const BOARD_PALETTE_WARNING := "Palette mismatch: asset %s, project %s; remap before final export"
const BOARD_ANIMATION_NEEDS_FRAMES := "Select at least two static assets as frames"
const BOARD_ANIMATION_READY := "Animation created with %d frames"
const BOARD_EXPORT_DONE := "Board PNG and layers exported"
const BOARD_EXPORT_FAILED := "Board export failed"
const PROVIDER_SETTINGS_SAVED := "Credentials saved locally. Validate before using this provider."
const PROVIDER_SETTINGS_SAVE_FAILED := "Credentials could not be saved. Check local file permissions."
const PROVIDER_SETTINGS_VALIDATE_UNAVAILABLE := "This provider cannot validate credentials."
const STATUS_GRAPH_RUN_DONE := "Graph run complete: %d sprites"
const STATUS_GRAPH_RUN_FAILED := "Graph run failed"
const STATUS_GRAPH_RUN_FAILED_DETAIL := "Graph run failed: %s"
const STATUS_GRAPH_RUN_NEEDS_SELECTION := "Select a graph node or batch before running"
const STATUS_GRAPH_RUN_MISSING_GRAPH := "Selected graph is missing"
const STATUS_GRAPH_RUN_NO_BATCH := "Graph has no batch node"
const STATUS_GRAPH_RUN_MISSING_BATCH_CARD := "Batch card is missing"
const STATUS_GRAPH_RUN_MISSING_NODE_TYPE := "Cannot run graph with missing node type: %s"
const STATUS_GRAPH_CONNECT_FAILED := "Graph connection failed: %s"
const STATUS_GRAPH_CONNECT_DONE := "Graph connection added: %s.%s -> %s.%s"
const STATUS_GRAPH_EDGE_SELECTED := "Graph edge selected: %s.%s -> %s.%s"
const STATUS_GRAPH_EDGE_DELETED := "Graph edge deleted: %s.%s -> %s.%s"
const STATUS_GRAPH_NODES_DELETED := "Graph nodes deleted: %d nodes, %d edges removed"
const STATUS_GRAPH_EDIT_NEEDS_SELECTION := "Select an editable graph node"
const STATUS_GRAPH_EDIT_NOT_AVAILABLE := "Selected graph node has no editable parameters"
const STATUS_GRAPH_EDIT_FAILED := "Graph node parameters could not be updated"
const STATUS_GRAPH_EDIT_DONE := "Graph node parameters updated"
const STATUS_GRAPH_ADD_NEEDS_SELECTION := "Select a graph node or batch before adding a node"
const STATUS_GRAPH_ADD_FAILED := "Graph node could not be added"
const STATUS_GRAPH_ADD_DONE := "Graph node added: %s"
const GRAPH_NODE_MISSING_DISPLAY := "Missing: %s"
const GRAPH_NODE_GHOST_SUMMARY := "Install the missing node type to run"
const GRAPH_NODE_BADGE_MISSING := "Missing"
const GRAPH_NODE_BADGE_EDGE_ERROR := "Edge error"
const CLEANUP_TITLE := "Pixel Cleanup"
const CLEANUP_SELECTED_FORMAT := "%d selected"
const CLEANUP_PRESET_PRIOR_FORMAT := "Preset prior: %dpx"
const CLEANUP_AUTO_DETECT := "Auto detect grid"
const CLEANUP_RUN_RESAMPLE := "Run resample"
const CLEANUP_RUN_QUANTIZE := "Run quantize"
const CLEANUP_LABEL_SCALE := "Scale"
const CLEANUP_LABEL_OFFSET_X := "Offset X"
const CLEANUP_LABEL_OFFSET_Y := "Offset Y"
const CLEANUP_LABEL_RESAMPLE := "Resample"
const CLEANUP_LABEL_QUANTIZE := "Quantize"
const CLEANUP_LABEL_AUTO_K_STRATEGY := "Auto K Strategy"
const CLEANUP_LABEL_PALETTE := "Palette"
const CLEANUP_LABEL_MAX_COLORS := "Max Colors"
const CLEANUP_LABEL_DITHER := "Dither"
const CLEANUP_LABEL_STRENGTH := "Strength"
const CLEANUP_LABEL_CHROMA := "Chroma"
const CLEANUP_LABEL_DENSITY := "Density"
const CLEANUP_AUTO_K_TOOLTIP := "K-means is smoother for larger K, but slower."
const CLEANUP_CUSTOM_PALETTE_PREFIX := "Custom: %s"
const CLEANUP_IMPORT_PALETTE_ITEM := "Import custom palette..."
const CLEANUP_DELETE_PALETTE := "Delete Custom Palette"
const CLEANUP_APPLY := "Apply Cleanup"
const CLEANUP_CANCEL := "Cancel Cleanup"
const CLEANUP_NO_REPORT := "No cleanup report"
const CLEANUP_NON_SQUARE_WARNING := "\nNon-square grid warning"
const CLEANUP_REPORT_FORMAT := "Scale %.2f | Confidence %.2f\nColors %d | Output %s%s"
const DIALOG_IMPORT_PALETTE := "Import Custom Palette"
const DIALOG_PALETTE_ERROR := "Palette Import Error"
const PALETTE_IMPORT_FAILED := "Palette import failed."
const DIALOG_OPEN_PROJECT := "Open PixelForge Project"
const DIALOG_SAVE_PROJECT := "Save PixelForge Project"
const DIALOG_IMPORT_IMAGES := "Import Images"
const DIALOG_EXPORT_PNG := "Export PNG"
const DIALOG_EXPORT_OVERWRITE_TITLE := "Replace Existing Export?"
const DIALOG_EXPORT_OVERWRITE_BODY_FORMAT := "These files already exist:\n%s\n\nReplace them?"
const DIALOG_EXPORT_RESULT_TITLE := "Export Result"
const DIALOG_IMPORT_FAILED_TITLE := "Import Failed"
const DIALOG_IMPORT_FAILED_BODY_FORMAT := (
	"These files could not be imported:\n%s\n\n" + "Fix or replace them, then choose Retry Import."
)
const DIALOG_NOTICE := "Notice"
const DIALOG_RECOVERY := "Recover Autosave"
const DIALOG_RECOVERY_BODY_FORMAT := (
	"Autosave found:\n%s\n\nRecover it as an unsaved copy? "
	+ "The original project will not be overwritten."
)
const DIALOG_UNSAVED_TITLE := "Unsaved Changes"
const DIALOG_UNSAVED_BODY_FORMAT := (
	"Save changes before %s?\n\nSave keeps your work. "
	+ "Discard continues without saving. Cancel stays here."
)
const DIALOG_SAVE := "Save"
const DIALOG_DISCARD := "Discard"
const DIALOG_APPLY := "Apply"
const DIALOG_CANCEL := "Cancel"
const DIALOG_MATTE_TITLE := "Matte Background"
const DIALOG_SLICE_TITLE := "Slice Sprites"
const DIALOG_OUTLINE_TITLE := "Outline Sprite"
const DIALOG_GRAPH_NODE_PARAMS_TITLE := "%s Parameters"
const DIALOG_OPENAI_SESSION_TITLE := "OpenAI Session Key"
const DIALOG_PROVIDER_SETTINGS_TITLE := "AI Provider Settings"
const PROVIDER_SETTINGS_PROVIDER := "Provider"
const PROVIDER_SETTINGS_SECRET_SAVED := "Saved credential — enter a new value to replace"
const PROVIDER_SETTINGS_CAPABILITIES_FORMAT := (
	"Capabilities — text to image: %s | image to image: %s | transparent background: %s | "
	+ "native pixel: %s | max batch: %d"
)
const VALUE_YES := "Yes"
const VALUE_NO := "No"
const OPENAI_SESSION_EXPLANATION := (
	"The key stays in memory for this app session. "
	+ "It is not saved in settings, projects, or logs."
)
const OPENAI_SESSION_PLACEHOLDER := "sk-..."
const DIALOG_MATTE_NON_FLAT_TITLE := "Background Not Uniform"
const DIALOG_MATTE_NON_FLAT_BODY := (
	"The background is not a solid color.\n\n"
	+ "Try the Magic Wand tool to select the background, increase tolerance carefully, "
	+ "or slice directly if the image already has transparency."
)
const DIALOG_ONBOARDING_TITLE := "Welcome to PixelForge"
const DIALOG_ONBOARDING_BODY := (
	"Quick start:\n"
	+ "1. Drag images onto the canvas or use File > Import Images.\n"
	+ "2. Select a sprite and use Matte, Slice, or Outline.\n"
	+ "3. Select multiple sprites and create a Batch for whole-batch actions.\n"
	+ "4. Use the Pixel Cleanup panel to clean one sprite or a selected group."
)
const EMPTY_CANVAS_IMPORT_HINT := "Drop 1–5 images here, or choose Import Images to start."
const TOOL_MAGIC_WAND := "Magic Wand"
const TOOL_RECTANGLE := "Rectangle Select"
const TOOL_LASSO := "Lasso"
const MATTE_LABEL_MODE := "Mode"
const MATTE_LABEL_TOLERANCE := "Tolerance"
const MATTE_LABEL_FEATHER := "Feather"
const MATTE_MODE_FLOOD := "Flood from edge"
const MATTE_MODE_GLOBAL := "Global color key"
const MATTE_WARNING_NON_FLAT_BACKGROUND := "Background is not uniform. Use Magic Wand or raise tolerance carefully."
const SLICE_AUTO_MATTE := "Matte before slicing"
const SLICE_LABEL_MERGE_DISTANCE := "Merge Distance"
const SLICE_LABEL_MIN_AREA := "Minimum Area"
const SLICE_PREVIEW_COUNT_FORMAT := "%d segments found"
const OUTLINE_LABEL_TYPE := "Type"
const OUTLINE_LABEL_CORNER := "Corner"
const OUTLINE_LABEL_COLOR := "Color"
const OUTLINE_TYPE_OUTER := "Outer"
const OUTLINE_TYPE_INNER := "Inner"
const OUTLINE_CORNER_CROSS := "Cross"
const OUTLINE_CORNER_SQUARE := "Square"
const OUTLINE_COLORED := "Use colored outline"
const BATCH_DEFAULT_LABEL := "Batch"
const MOCK_BATCH_LABEL := "Mock Batch"
const OPENAI_BATCH_LABEL := "OpenAI Batch"
const OPENAI_V1_FIXED_PROMPT := "a wooden barrel game sprite for a 16-bit farming game"
const BATCH_ACTION_CLEANUP := "Clean Batch"
const BATCH_ACTION_MATTE := "Matte Batch"
const BATCH_ACTION_OUTLINE := "Outline Batch"
const BATCH_ACTION_QUANTIZE := "Quantize Batch"
const BATCH_ACTION_MARK_KEEP := "Mark Keep"
const BATCH_ACTION_MARK_REJECT := "Mark Reject"
const BATCH_ACTION_MARK_FLAG := "Flag"
const BATCH_ACTION_CLEAR_MARK := "Clear Mark"
const BATCH_ACTION_SHOW_ALL := "Show All"
const BATCH_ACTION_SHOW_KEEP := "Show Keep"
const BATCH_ACTION_SHOW_PENDING := "Show Pending"
const BATCH_ACTION_SHOW_REJECT := "Show Reject"
const BATCH_ACTION_SHOW_FLAG := "Show Flagged"
const BATCH_ACTION_LAYOUT_CONTACT := "Contact Sheet"
const BATCH_ACTION_LAYOUT_FOCUS := "Focus View"
const BATCH_ACTION_COMPARE_CURRENT := "Show Current"
const BATCH_ACTION_COMPARE_PREVIOUS := "Show Previous"
const BATCH_ACTION_COMPARE_SPLIT := "Show Compare"
const BATCH_COMPARE_PREVIOUS_SUFFIX := "previous"
const BATCH_COMPARE_SPLIT_SUFFIX := "compare"
const BATCH_INSPECT_HINT_FORMAT := "%dx%d, %d colors"
const BATCH_INSPECT_HINT_CAPPED_FORMAT := "%dx%d, %d+ colors"
const BATCH_ACTION_SPLIT_KEEP := "Split Kept"
const BATCH_ACTION_SPLIT := "Split Selected"
const BATCH_ACTION_EXPORT := "Export Batch"
const BATCH_ACTION_SEND_TO_EDITOR := "Send to Editor"
const BATCH_KEEP_LABEL_SUFFIX := "keep"
const GRAPH_PARAM_OBJECT_LIST := "Objects"
const GRAPH_PARAM_WIDTH := "Width"
const GRAPH_PARAM_HEIGHT := "Height"
const GRAPH_PARAM_PER_SUBJECT := "Per Subject"
const GRAPH_PARAM_PROVIDER := "Provider"
const GRAPH_PARAM_BATCH_SIZE := "Batch Size"
const GRAPH_PARAM_SEED := "Seed"
const GRAPH_PARAM_UNKNOWN_FORMAT := "%s"
